"""GD SPL snippet build: render a C body into a regcmp_test TU and link a
thumbv7m ELF against the local GD SPL source.

The body is wrapped in ``regcmp_test`` (the fixed entry symbol). It is compiled
with ``arm-none-eabi-gcc -mcpu=cortex-m3 -mthumb``, the family chip-define,
``-DUSE_STDPERIPH_DRIVER``, the SPL + CMSIS include dirs (from the bench config)
with the vendored cmsis-stubs first, and linked with the vendored startup.S +
link.ld plus the needed SPL ``.c`` files. ``--gc-sections`` keeps unrelated SPL
code out; KEEP(regcmp_test) in the link script prevents the entry being dropped.
The extractor enters at regcmp_test with LR = sentinel, so SystemInit/main never
run and only the snippet body's MMIO is captured.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from . import paths

# Pinned compile flags. -ffreestanding/-fno-builtin keep unrelated runtime out;
# -std=gnu11 because the SPL typedefs `bool` (a keyword under C23+). Warnings the
# vendor SPL trips are demoted, not silenced globally.
SPL_CFLAGS = (
    "-Os", "-mcpu=cortex-m3", "-mthumb", "-fno-common", "-ffreestanding",
    "-fno-builtin", "-std=gnu11", "-Wall",
    # -ffunction-sections so --gc-sections can prune unused SPL functions (e.g.
    # gpio_deinit, which would otherwise pull in the rcu reset driver).
    "-ffunction-sections", "-fdata-sections",
    "-Wno-unused-but-set-variable", "-Wno-unused-variable", "-Wno-comment",
)

# Which SPL .c file a given peripheral group maps to, per family. The .c file
# name is just the family prefix + the peripheral group. usart_baudrate_set
# calls rcu_clock_freq_get, so a usart vector also needs the rcu driver linked.
SPL_PERIPHERAL_GROUPS = ("gpio", "rcu", "usart", "fmc", "i2c", "spi", "adc", "timer")


def spl_source(family: str, group: str) -> str:
    return f"{family}_{group}.c"


# Back-compat alias used by older callers/tests.
SPL_SOURCES_F1X0 = {g: [spl_source("gd32f1x0", g)] for g in SPL_PERIPHERAL_GROUPS}


@dataclass(frozen=True)
class SplBuildResult:
    elf_path: Path
    family: str
    chip_define: str
    compile_cmd: list[str]
    gcc_version: str


def gcc_version() -> str:
    out = subprocess.check_output(
        [f"{paths.toolchain_prefix()}gcc", "--version"], text=True
    )
    return out.splitlines()[0].strip()


def render_source(body: str, includes: list[str]) -> str:
    inc = "\n".join(f"#include <{h}>" for h in includes)
    return f"""\
/* Generated by regcmp harness from a vector body. Do not edit. */
{inc}

__attribute__((noinline, used))
void regcmp_test(void)
{{
{body.rstrip()}
}}
"""


def build(
    family: str,
    body: str,
    includes: list[str],
    spl_sources: list[str],
    out_elf: Path,
) -> SplBuildResult:
    layout = paths.spl_layout(family)
    src_dir = Path(layout["src_dir"])
    chip_define = layout["chip_define"]
    include_dirs = [Path(d) for d in layout["include_dirs"]]
    assets = paths.build_assets_dir("gd-spl", family)
    stubs = assets / "cmsis-stubs"
    startup = assets / "startup.S"
    link_ld = assets / "link.ld"
    for p in (startup, link_ld, stubs):
        if not p.exists():
            raise RuntimeError(f"missing build asset: {p}")

    out_elf.parent.mkdir(parents=True, exist_ok=True)
    src_files = [src_dir / s for s in spl_sources]
    for s in src_files:
        if not s.exists():
            raise RuntimeError(f"SPL source not found: {s}")

    snippet_dir = out_elf.parent
    snippet_c = snippet_dir / f"{out_elf.stem}.snippet.c"
    snippet_c.write_text(render_source(body, includes))

    gcc = f"{paths.toolchain_prefix()}gcc"
    if shutil.which(gcc) is None:
        raise RuntimeError(f"{gcc} not on PATH")

    cmd = [
        gcc,
        *SPL_CFLAGS,
        f"-D{chip_define}",
        "-DUSE_STDPERIPH_DRIVER",
        # cmsis-stubs first so our core_cmInstr/core_cmFunc + libopt win.
        f"-I{stubs}",
        *(f"-I{d}" for d in include_dirs),
        "-nostartfiles",
        "-T", str(link_ld),
        str(startup),
        str(snippet_c),
        *(str(s) for s in src_files),
        "-o", str(out_elf),
        "-Wl,--gc-sections",
    ]
    subprocess.check_call(cmd)
    return SplBuildResult(
        elf_path=out_elf,
        family=family,
        chip_define=chip_define,
        compile_cmd=cmd,
        gcc_version=gcc_version(),
    )
