"""runtime-hal Rust snippet build: a tiny no_std thumbv7m staticlib that calls
one runtime-hal path function, linked into an ELF exposing regcmp_test.

Mechanism (the pinned decision, plan section 5.1): a permanent checked-in
template crate at ``harness/snippet-crate/`` whose single generated module
(``src/snippet_body.rs``) is swapped per vector, then restored. cargo's
incremental cache makes the per-vector matrix fast. The crate depends on
runtime-hal as a path dep with default features (real volatile MMIO, NOT
``mock``), so Reg writes hit Unicorn-backed memory.

``regcmp_test`` survives optimisation via ``#[no_mangle]`` + a ``#[used]`` static
referencing it + ``KEEP(.text.regcmp_test)`` in the link script, with LTO off so
the path-fn call is not inlined to nothing observable. The base constants the
generated body passes equal the target file's bases, so symbols resolve to the
golden's addresses.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from . import paths

RUST_TARGET = "thumbv7m-none-eabi"
STATICLIB_NAME = "libregcmp_snippet.a"


@dataclass(frozen=True)
class RustBuildResult:
    elf_path: Path
    staticlib: Path
    family: str
    rustc_version: str


def rustc_version() -> str:
    return subprocess.check_output(["rustc", "--version"], text=True).strip()


def _wrap_body(rust_body: str) -> str:
    """Wrap a vector's Rust body in the snippet_body module's `body()` fn."""
    return f"""\
//! Generated by regcmp build_rusthal.py from a vector body. Do not edit.
#![allow(unused_imports)]

{rust_body.rstrip()}
"""


def build(family: str, rust_body: str, out_elf: Path) -> RustBuildResult:
    crate = paths.snippet_crate_dir()
    body_file = crate / "src" / "snippet_body.rs"
    original = body_file.read_text()
    out_elf.parent.mkdir(parents=True, exist_ok=True)

    try:
        body_file.write_text(_wrap_body(rust_body))
        subprocess.check_call(
            ["cargo", "build", "--release", "--target", RUST_TARGET],
            cwd=str(crate),
        )
    finally:
        # Always restore the checked-in default body so the working tree is clean.
        body_file.write_text(original)

    staticlib = crate / "target" / RUST_TARGET / "release" / STATICLIB_NAME
    if not staticlib.exists():
        raise RuntimeError(f"staticlib not produced: {staticlib}")

    # build_assets/runtime-hal/ (no per-family subdir: the Rust snippet's
    # startup + link script are family-independent; the body picks the path).
    assets = paths.harness_root() / "build_assets" / "runtime-hal"
    startup = assets / "startup.S"
    link_ld = assets / "link.ld"
    for p in (startup, link_ld):
        if not p.exists():
            raise RuntimeError(f"missing build asset: {p}")

    gcc = f"{paths.toolchain_prefix()}gcc"
    if shutil.which(gcc) is None:
        raise RuntimeError(f"{gcc} not on PATH")

    cmd = [
        gcc,
        "-mcpu=cortex-m3", "-mthumb",
        "-nostartfiles", "-nostdlib",
        "-T", str(link_ld),
        str(startup),
        # Whole-archive so the staticlib's regcmp_test (and the path fn it calls)
        # is pulled in even though _start references it across the link.
        "-Wl,--whole-archive", str(staticlib), "-Wl,--no-whole-archive",
        "-o", str(out_elf),
        "-Wl,--gc-sections",
        # compiler-rt helper objects (e.g. umodsi3) lack a .note.GNU-stack
        # section; this is a bare-metal ELF, so silence the execstack warning.
        "-Wl,--no-warn-execstack",
    ]
    subprocess.check_call(cmd)
    return RustBuildResult(
        elf_path=out_elf,
        staticlib=staticlib,
        family=family,
        rustc_version=rustc_version(),
    )
